### ISSUE TITLE
Custom Wrapper location

### ISSUE THREAD

**Issue by vinsworldcom** [adjacentlink/python-etce#4]
From https://github.com/adjacentlink/python-etce/wiki/Extending-ETCE:

"Wrappers are installed in a known (configurable) location [...]"

How does one "configure" the location?  Or is it simply the `/usr/lib/python*/site-packages/*` path and subdirectories?  Can one specify a Wrapper directory local to the test directory, for example:

[etceuser@host]$ tree 04.templates
04.templates
|__ doc
|__ helper
|__ node.tpl
|__ steps.xml
|__ test.xml
|_ MyWrappers
|____ MyNewWrapper.py
|____ MyCustomWrapper.py
|____ SpecDir
|________ SuperSpecial.py

The in some config file:
CustomWrapperDir = MyWrappers

Cheers.

**Comment by eschreiber-alink** [comment]
The Extending-ETCE wiki page was a bit out of date - I've updated it. Wrappers are installed into the `etcewrappers` Python namespace package. Place your wrappers into a sub-package under `etcewrappers` - for example, etcewrappers/mywrappercollection/mywrapper.py. An `etcewrappers/mywrappercollection/__init__.py` file will also be required.

**Comment by vinsworldcom** [comment]
Understood.  That's what I figured, what we did and what worked.  I just wanted to see if there was an alternate local way.  The Python package route should work fine in our case.
