### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by vinsworldcom** [adjacentlink/python-etce#5]
Are there plans to make python-etce fully support running under Python3?

**Comment by eschreiber-alink** [comment]
Yes, it will be updated to fully support Python 3.

**Comment by vinsworldcom** [comment]
Thanks, I'll keep checking back.

**Comment by vinsworldcom** [comment]
I see [v1.2.2](https://github.com/adjacentlink/python-etce/releases/tag/v1.2.2) does Python3 - Thanks!
